name: Terraform Plan
on:
  push:
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform*'
  pull_request:
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform*'

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan
