name: Terraform Apply

on:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform-*.yml'
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type APPLY to confirm applying Terraform'
        required: true
        default: 'DRYRUN'

permissions:
  contents: read

concurrency:
  group: tf-apply-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: infra/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate manual approval
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "APPLY" ]; then
            echo "You must enter 'APPLY' to proceed." >&2
            exit 1
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan (for visibility)
        run: terraform plan -input=false -no-color -out=tfplan
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
