name: Terraform Apply
on:
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      # Option A: re-plan+apply directly (simple)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # Option B (safer): download & apply the last plan artifact from the Plan workflow
      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform

      - name: Terraform Apply (from plan)
        run: terraform apply -input=false -auto-approve tfplan
